### PR TITLE
#22 Migrate: `Ohara Manager Development Guideline`

### PR DESCRIPTION
**Pull request by vitojeng**
required by #22

### CODE REVIEW

**Comment by vitojeng** [comment]
@konekoya 只加了 front matter, 其餘一刀未剪

**Comment by konekoya** [comment]
> @konekoya 只加了 front matter, 其餘一刀未剪

XXD, thanks ❤️

**Comment by vitojeng** [comment]
rebase master and force-push

**Comment by konekoya** [comment]
@vitojeng I somehow cannot add you as the reviewer... could you help review this PR? Manager's docs are outdated, i will open another PR to update it :)

**Comment by vitojeng** [comment]
LGTM!

**Pull request merged**
